name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Autograding Tests - Subject
      id: autograding-tests-subject
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Autograding Tests - Subject
        setup-command: "./gradlew build"
        command: "./gradlew test"
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        AUTOGRADING-TESTS-SUBJECT_RESULTS: "${{steps.autograding-tests-subject.outputs.result}}"
      with:
        runners: autograding-tests-subject
